version: '3'

services: 
  app:
    build:
      context: . 
    ports: 
      - 8000:8000 # vai receber da porta 8000 do localhost
    volumes:
      - tasks-api-db:/app # Persistência do db
      - ./assignments:/app/assignments 
      - ./user:/app/user 
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.docker.env
volumes:
  tasks-api-db: