# Generated by Django 4.0.3 on 2022-05-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_category_assignment_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="used",
            field=models.IntegerField(blank=True, default=1, verbose_name="Usada"),
        ),
    ]
