# Generated by Django 4.0.3 on 2022-05-31 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0004_alter_category_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador da tarefa",
            ),
        ),
    ]
